### ISSUE TITLE
Question on install

### ISSUE THREAD

**Issue by Rouzax** [ajarzyn/domoticz-luxtronic2#2]
No bug, just a question 😄. Found this plugin through Tweakers/Domoticz forum
Have a Domoticz setup running at home and an Alpha Innotec WZSV 92K3M and would want to try/test this plugin.
Is there any explanation on how to set this up?
Is it just a Domoticz Plugin, do I need to pre create the devices, where do I need to enter de idx mappings.

Have looked through the python script but it is not really clear to me.

**Comment by ajarzyn** [comment]
Hello,

1. Add it just like as a usual plugin to the plugin directory (depending on you installation ie. /config/plugins/domoticz-luxtronic2)
2. Restart Domoticz
3. Open Hardware tab and add new hardware of the Type: Luxtroni2 based on sockets.
4. Fill IP of you luxtronic, and port (default should be 8889)

And you are done.
I will add it to README but there are tone of project I'm trying to finish rght now.

And hopefully I will find some time to update this script with few additional features.
For now only Changing mode for Heating, Hot water, and Cooling are working as a luxtronic input.

Let me know if you miss any other option I will try to look into that.

**Comment by Rouzax** [comment]
Would it be wise to do a git clone in that location, or can/will there be breaking changes with updates?

**Comment by ajarzyn** [comment]
No breaking changes.

You can simply create file and copy code into plugin.py, and for updating just copying new code.
Personally I like this solution as my plugins files are available from the web interface thus I can simply update them from there.

I know that there are people intrested in this plugin already thus I'm not going to change anything that would affect end users of this script.

In this point I'm mostly reffering to Devices ID, as they are generated automatically based on the list order.
Thus only one thing to keep on my mind is not to add any new Device before last one on the list.

I was thinking on implementing "update" mechanizm for the Devices so this way I could manipulate them anyway I like, leaving the list consistent and clean to read.

Offtopic:
Would you like to share/talk privately regarding heatpump working parameters. I'm very curious of the lenght and count of the cycle for heating, but I would like to spam on the git thread and rather have e-mail, private communicator conversation.
(But I do not know how to share such information as email though git keeping it private)

**Comment by Rouzax** [comment]
Yes, sure. You should be able to find my github email on my profile.
Only just recently have a new home with a heat pump so still pretty novice for me 😄 

EDIT:
Shouldn't the path be `domoticz/plugins/domoticz-luxtronic2`

**Comment by Rouzax** [comment]
Installed it and it works
![image](https://user-images.githubusercontent.com/4103090/144576987-09b64a49-a254-422b-a983-d77899c7f32e.png)

**Comment by ajarzyn** [comment]
> EDIT: Shouldn't the path be `domoticz/plugins/domoticz-luxtronic2`

It depends on the configuration you use.


> Installed it and it works

Good it works. I've used it for quite a while now did not have any issues.

**Comment by Rouzax** [comment]
Only thing that seems to stay empty are these Utility meters
![image](https://user-images.githubusercontent.com/4103090/144585272-b77e5c95-5310-4d8a-87b6-69544c75238c.png)

Under devices I do see that they hold some values.
![image](https://user-images.githubusercontent.com/4103090/144585416-216feaee-ed09-4dfa-8809-167b08b42f14.png)

Is this a matter of just waiting 😃

**Comment by ajarzyn** [comment]
Those are values of energy produced by you heatpump so far.
I must find better domoticz device for it as devices used (kWh) like to get currect energy value - which is not available.

I'm using it to redirect this data to the influxdb. But it's on my todo list.

**Comment by Rouzax** [comment]
So that is the same information as this from heatpump24.com
![image](https://user-images.githubusercontent.com/4103090/144587296-111f0186-fccd-4533-b9bf-c8fbf7032937.png)

**Comment by Rouzax** [comment]
Would you be able to also pick up the compressor frequency?
See that this project for HA is able to retrieve it.
https://github.com/Bouni/luxtronik

**Comment by ajarzyn** [comment]
> So that is the same information as this from heatpump24.com

You do not have to login to heatpump24.com to check this information.
Just go to your heatpump ip addres from the browser and press ok, to log in and get some information.
You can also hit 999999 password and you will get some basic configuration too.



> Would you be able to also pick up the compressor frequency? See that this project for HA is able to retrieve it. https://github.com/Bouni/luxtronik

Sure I will be adding more sensors later as I will have some time to spare.
You could write all the sensor you are intrested in in feature request.

Hopefully I will be able to draw some "TODO" list :)

**Comment by ajarzyn** [comment]
> Would you be able to also pick up the compressor frequency? See that this project for HA is able to retrieve it. https://github.com/Bouni/luxtronik

Could you please point me to where/which device is the compressor frequency? Which device you are interested in.

Is it maybe PWM: 183: Percent2("ID_WEB_HZIO_PWM")?

**Comment by Rouzax** [comment]
I'm trying to figure it out :)
The 2 on the right are the values I'm looking for, this is the comprossor frequency,
The ones on the left (current temp and temp set point) would also be nice to have.
![image](https://user-images.githubusercontent.com/4103090/145674325-673fd6a4-913e-4929-8497-cdf05e739bad.png)

**Comment by Rouzax** [comment]
I think it is https://github.com/Bouni/python-luxtronik/blob/master/luxtronik/calculations.py#L265

**Comment by ajarzyn** [comment]
As I understand translation correctly.
Left temperatures are retrieved from the room panel? (I do not have one, and I can't neither test it but could implement it if I have an index and the multiplier).

Regarding frequencies I've only added Compressor frequency, as I can see in name which index is that, but I'm not certain too as my device does not display this information. (The raw version is on my local PC, I have to clean the file a bit before uploading sorry)

If you can test/investigate it at your end that would probably solve it.
How to investigate?


Assuming you use linux:
[ Bouni / Luxtronik-2 ](https://github.com/Bouni/Luxtronik-2)
Download repo
`git clone git@github.com:Bouni/Luxtronik-2.git`
`cd Luxtronik-2`
modify luxtronik-2.py file
line 119: set ip of your device
remove line 123 (we do not need that information)
save the file and run:
`python3 luxtronik-2.py`

look for data similar to one from web interface
for example 
Act. rimtetemp. would be 215
Gew. rumitetemp would be 240
I do not know about Feq. but from what I found out idx 231 for calculated is Compressor frequency, I do not know multiplier thou.

Good luck and have fun.

**Comment by Rouzax** [comment]
Thanks will run it coming week, when I have some spare time 😁

**Comment by ajarzyn** [comment]
New version is out. Please test if it works well.
If there would be any problem (because of big changes). Please delete and add hardware back again.

Sorry for trouble.

**Comment by Rouzax** [comment]
Temperature = Calculation 228
Temperature Set Point = Calculation 227

To update, stop Domoticz, git pull, start Domoticz?

**Comment by Rouzax** [comment]
After upgrading like this, all seems to work, and I do get additional devices.
However, the Working Mode now gives a numeric value of `600` instead of the text field `Heating Mode`

Deleted the WP Hardware and added it again, afterwards all devices show up properly
Do get these 2 errors during first start of the plugin
```
2021-12-13 08:53:16.482  Error: (WP) Failed to initialize Options dictionary for Hardware/Unit combination (11:17): Only "string" type dictionary entries supported, but entry has type "int"
2021-12-13 08:53:16.483  Error: (WP) Failed to initialize Options dictionary for Hardware/Unit combination (11:18): Only "string" type dictionary entries supported, but entry has type "int"
```

**Comment by ajarzyn** [comment]
Select hardware 
![image](https://user-images.githubusercontent.com/18590439/145779055-eb91ef45-6ff9-452a-ae35-a2311d3bb00f.png)
-> Delete 
![image](https://user-images.githubusercontent.com/18590439/145778962-658c3d9b-c979-43e3-9f88-8cde3adb137b.png)
-> Add 
![image](https://user-images.githubusercontent.com/18590439/145779011-10941316-eeb5-4158-aedd-b30c3ac71261.png)

If you do this this way, all plugin settings will be there, but unfortunatelly history will be lost. Indexes of the devices have been changed sorry for that.

**Comment by ajarzyn** [comment]
> Temperature = Calculation 228 Temperature Set Point = Calculation 227

Pleas correct if I'm wrong (english translation at the very end of the line) is it correct?
Calculation:
227 | ID_WEB_RBE_RT_Ist | RBE_RT_Ist | temperature | 10 | °C |   |   | Raumtemperatur Ist - 'Actual room temperature'
228 | ID_WEB_RBE_RT_Soll | RBE_RT_Soll | temperature | 10 | °C |   | Raumtemperatur Soll - 'Room temperature set'


Additionally if you would like to try to add `Room temperature set` as a selector we probably could do that but you will need to do some more digging.

1. Verify which Parameters read has the same value as the Calculated read:

Check Parameters:
35 | ID_Visi_Temp_Raumstation

228 | ID_Visi_Temp_Raumstation2 |   |   |  
229 | ID_Visi_Temp_Raumstation3 |   |   |  

2. When you find the value that match you can try to save it with script I previously linked:
```if __name__ == "__main__":
    lt = Luxtronic2('192.168.88.11',8889)
    lt.connect()
    address = 229 # this shall be address that matches value of the temperature set
    value = 230 # remember here that temperature value is multiplied by 10 thus 230 is 23.0 in reality
    lt.set_parameter(address, value)
    lt.get_calculated()

    lt.dump()
```
3. and check on the panel/in android app  that the set point was updated.

If it all work well, let me know which parameter address is that and we can add switch for this.

**Comment by ajarzyn** [comment]
I've added 2 of your thermometer devices. Please test it. f28d13e

**Comment by Rouzax** [comment]
> > Temperature = Calculation 228 Temperature Set Point = Calculation 227
> 
> Pleas correct if I'm wrong (english translation at the very end of the line) is it correct? Calculation: 227 | ID_WEB_RBE_RT_Ist | RBE_RT_Ist | temperature | 10 | °C |   |   | Raumtemperatur Ist - 'Actual room temperature' 228 | ID_WEB_RBE_RT_Soll | RBE_RT_Soll | temperature | 10 | °C |   | Raumtemperatur Soll - 'Room temperature set'
> 
> Additionally if you would like to try to add `Room temperature set` as a selector we probably could do that but you will need to do some more digging.
> 
>     1. Verify which Parameters read has the same value as the Calculated read:
> 
> 
> Check Parameters: 35 | ID_Visi_Temp_Raumstation
> 
> 228 | ID_Visi_Temp_Raumstation2 |   |   |   229 | ID_Visi_Temp_Raumstation3 |   |   |
> 
>     2. When you find the value that match you can try to save it with script I previously linked:
> 
> 
> ```
>     lt = Luxtronic2('192.168.88.11',8889)
>     lt.connect()
>     address = 229 # this shall be address that matches value of the temperature set
>     value = 230 # remember here that temperature value is multiplied by 10 thus 230 is 23.0 in reality
>     lt.set_parameter(address, value)
>     lt.get_calculated()
> 
>     lt.dump()
> ```
> 
>     3. and check on the panel/in android app  that the set point was updated.
> 
> 
> If it all work well, let me know which parameter address is that and we can add switch for this.

Exactly the other way around 😄 
228 is the current actual room temp
227 is the desired temp set point

Flow and Compressor Frequency also show correct.
![image](https://user-images.githubusercontent.com/4103090/145797439-eddc67b1-a5d6-47db-9971-4a0b0e20c29e.png)
![image](https://user-images.githubusercontent.com/4103090/145797392-9db0b893-baad-4623-93ef-ee234e09db7a.png)
Can't say for sure if the Frequency shown in Domoticz is the actual Freq or the desired Freq.

**Comment by ajarzyn** [comment]
> Exactly the other way around 😄
> 228 is the current actual room temp
> 227 is the desired temp set point

Last change I've made according to this [file](https://github.com/Bouni/Luxtronik-2/blob/master/documentation.md#3004)
Please test it and confirm that temperatures are swaped. If so I will do an update.

**Comment by Rouzax** [comment]
I can't find any other ID that has the value 220 for the Temperature Set point.
Will try to export, change the temp and export again and do a compare.

EDIT:
There are no `Parameters` changed when setting my temp from 22 to 24, all of them stay the same.

EDIT2:
The room temp set point and actual temp are correct
![image](https://user-images.githubusercontent.com/4103090/145800650-09a62305-83b6-493a-9bf8-9c2da95b08d2.png)

**Comment by ajarzyn** [comment]
> I can't find any other ID that has the value 220 for the Temperature Set point.

Shouldn't you look for 240?
Are you sure you are checking Parameters `lt.get_parameters()`? (It has around 1061 different fields in it)
Maybe it is in different place try to look for 240 value. Or maybe it's not possible to change that value from the socket.


> EDIT:
> There are no `Parameters` changed when setting my temp from 22 to 24, all of them stay the same.

You can try to look under different indexes.

> EDIT2:
> The room temp set point and actual temp are correct

Documents is correctly written after all.

> Can't say for sure if the Frequency shown in Domoticz is the actual Freq or the desired Freq.

You would need to observe it's behaviour, additionally if you would like to have second value you would need to investigatge it by yourself (as with temperatures) I do not have access to the device with this values shown.

Look how many different values you have that I do not:
![image](https://user-images.githubusercontent.com/18590439/145804156-820577d9-d0c0-4738-8a1d-3149a0eeacfe.png)

**Comment by ajarzyn** [comment]
Found out why I do not have Frequency!

Your heat pump has an inverter.
Mine does not.

**Comment by Rouzax** [comment]
> Found out why I do not have Frequency!
> 
> Your heat pump has an inverter. Mine does not.

You mean that mine can throttle power based on demand, whereas yours is either on or off?

> Shouldn't you look for 240?

I indeed looked for 220 when that was set and 240 when that was set, also did a compare between the 2 and found that no `Parameters` changed.
Can also not set the room temp from the Heat pump website itself, so it looks to be something that can only be set from the RBE+

**Comment by ajarzyn** [comment]
> You mean that mine can throttle power based on demand, whereas yours is either on or off?

Yup that's exactly what I meant.


> can only be set from the RBE+

It's possible I do not know I do not have access to this device.

Anyway, all is set here I think we can close this thread, what do you think?
Some additional features will appear in the future, but I would like to focus on different project now.

**Comment by Rouzax** [comment]
I agree, thanks for your help!

**Comment by ajarzyn** [comment]
Stay tuned for update, and if you find any other device you would like to have in your domoticz open new issue.
Best to you.
