### ISSUE TITLE
[BUG] - values will report 0 in Domoticz if Heatpump is off

### ISSUE THREAD

**Issue by Rouzax** [ajarzyn/domoticz-luxtronic2#6]
**Describe the bug**
Had to take my heatpump offline, as a result the plugin is reporting 0 values for all devices.
Would it be possible to not write any results if Heatpump is inaccessible?

**Comment by ajarzyn** [comment]
Hi,

Thanks for this notice, will see into it.
I did not expect someone would like to turn heat pumpt off rather expected to turn off the mode.

**Comment by Rouzax** [comment]
In my case they needed to service the Luxtronic controller, so it needed to be shutdown.

**Comment by ajarzyn** [comment]
Hello,

I need more details regarding this issue.
What do you mean by turning off the Heat pump?

If heat pump is off then controller is off thus no connection with heat pump.
No update should be pushed.

I've tested it with changing IP for my plugin to incorrect value, but no data was written.

Where and how this data was updated? (Domoticz/Grafana)
Have you checked with CSV file that 0 values are updated in the devices?

Could you please provide logs?

**Comment by Rouzax** [comment]
In my case the Heatpump was unplugged and then either during the offline period or during boot of the heatpump it will register 0 values.
I'll try to replicate it with all debug logging on in the plugin enabled.
Values were seen in Domoticz, have since manually deleted the 0 values from the DB

**Comment by ajarzyn** [comment]
I would really appreciate logs.

I could sanitize the data received from heat pump, but I do not know which data should be sanitized, what kind of check would define that heatpump is in the state that data shouldn't be red from.

I do not want to guess as it can lead to many unforeseen problems.

**Comment by ajarzyn** [comment]
@Rouzax any luck gatherin logs?

**Comment by Rouzax** [comment]
Sorry no not yet, currently on holiday and was also busy with some troubleshooting in Domoticz.
Will try to get this done in the coming week.
